#!/bin/sh

# This script takes whatever is copied to my clipboard and adds it to
# my bookmarks file. If the bookmark already exists, it notifies me.

selection="$(wl-paste)"

replace=""
rm1=${selection/https:\/\/www./$replace}
rm2=${rm1/https:\/\//$replace}

bookmark=${rm2/www./$replace}

file="$HOME/docs/bookmarks"

if [[ -z "$bookmark" ]]; then
    notify-send "Nothing selected to bookmark"
elif grep -q "^$bookmark$" "$file"; then
    notify-send "Bookmark already exists"
else
    echo "$bookmark" >> "$file"
    sed -i '/^$/d' $file
    sort -o $file{,}
    notify-send "Bookmark added"
fi
