#!/bin/sh

# This script shows a wofi / dmenu list of the bookmarks I have
# It also adds the https prefix to the start of the string
# At the moment it adds the selection to the clipboard
# I would also like it to paste to the textbox of current focus

bookmarks=~/docs/bookmarks

item=$(grep -v '#^' $bookmarks | wofi --dmenu -p "Bookmark:")
prefix="https://"
selection="$prefix$item"

if [ "$selection" == "$prefix" ]; then
    echo $(wl-copy "")
else
    echo $(wl-copy $selection)
    echo $(wl-paste)
fi
