#!/usr/bin/env bash

# This script deletes all the files in my docs/dotfiles folder and replaces them

# / Remove what is currently there
rm ~/docs/dotfiles/.zshenv
rm ~/docs/dotfiles/.profile
rm -r ~/docs/dotfiles/config/*
rm -r ~/docs/dotfiles/local/*

# Make directories for select file copies
mkdir ~/docs/dotfiles/config/bash/
mkdir ~/docs/dotfiles/config/tmux/
mkdir ~/docs/dotfiles/config/zsh/

# Copy home directory files
cp ~/.zshenv ~/docs/dotfiles/
cp ~/.profile ~/docs/dotfiles/

# Copy dotfiles
cp -ar ~/.config/alacritty/ ~/docs/dotfiles/config/
cp -ar ~/.config/bash/.bashrc ~/docs/dotfiles/config/bash/
cp -ar ~/.config/dunst/ ~/docs/dotfiles/config/
cp -ar ~/.config/fastfetch/ ~/docs/dotfiles/config/
cp -ar ~/.config/i3/ ~/docs/dotfiles/config/
cp -ar ~/.config/kitty/ ~/docs/dotfiles/config/
cp -ar ~/.config/nvim/ ~/docs/dotfiles/config/
cp -ar ~/.config/picom/ ~/docs/dotfiles/config/
cp -ar ~/.config/polybar/ ~/docs/dotfiles/config/
cp -ar ~/.config/tmux/tmux.conf ~/docs/dotfiles/config/tmux/
cp -ar ~/.config/X11/ ~/docs/dotfiles/config/
cp -ar ~/.config/zsh/.zshrc ~/docs/dotfiles/config/zsh/

# Copy personal local folders
cp -ar ~/.local/scripts/ ~/docs/dotfiles/local/

echo "copy completed"
