#
# ~~ ~~ ~~ ~~ ~~ ~~ ~~ ~~
# ~~ ALACRITTY  CONFIG ~~
# ~~ ~~ ~~ ~~ ~~ ~~ ~~ ~~
#

general.import = [
  "~/.config/alacritty/themes/oldworld.toml"
]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"

[font]
normal.family = "GeistMono Nerd Font"
normal.style = "regular"
size = 19

[window.padding]
x = 10
y = 10

[window]
opacity = 1.0

[scrolling]
history = 10000
multiplier = 4

