[wifi]
disable=True

[connections]
disable=True

[fs]
disable=True

[network]
disable=True

[diskio]
disable=True

[raid]
disable=True

[sensors]
disable=True

[ports]
disable=True

[folders]
disable=True

[irq]
disable=True

[quicklook]
disable=True

[ip]
disable=True
